// Firestore collection: 'posts'
const postStructure = {
  postId: 'string', // Auto-generated by Firestore
  authorId: 'string', // UID of the author
  authorName: 'string',
  authorAvatar: 'string', // URL to the author's profile picture
  title: 'string',
  content: 'string',
  media: ['string'], // Array of URLs to images/videos
  // timestamp: firebase.firestore.Timestamp,
  likes: 'number',
  comments: 'number',
  tags: ['string'], // Optional
};
